//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnboardingRrhh.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbOnboardingEntities : DbContext
    {
        public DbOnboardingEntities()
            : base("name=DbOnboardingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ORTAsignacionRecurso> ORTAsignacionRecurso { get; set; }
        public virtual DbSet<ORTColaborador> ORTColaborador { get; set; }
        public virtual DbSet<ORTDepartamento> ORTDepartamento { get; set; }
        public virtual DbSet<ORTEstadoSkill> ORTEstadoSkill { get; set; }
        public virtual DbSet<ORTEstadoWill> ORTEstadoWill { get; set; }
        public virtual DbSet<ORTEvaluacion> ORTEvaluacion { get; set; }
        public virtual DbSet<ORTOnboarding> ORTOnboarding { get; set; }
        public virtual DbSet<ORTPlaza> ORTPlaza { get; set; }
        public virtual DbSet<ORTRamaSkill> ORTRamaSkill { get; set; }
        public virtual DbSet<ORTRecurso> ORTRecurso { get; set; }
        public virtual DbSet<ORTSkill> ORTSkill { get; set; }
        public virtual DbSet<ORTSkillEvaluacion> ORTSkillEvaluacion { get; set; }
        public virtual DbSet<ORTWill> ORTWill { get; set; }
        public virtual DbSet<ORTWillEvaluacion> ORTWillEvaluacion { get; set; }
    }
}
