//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnboardingRrhh.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORTEstadoWill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORTEstadoWill()
        {
            this.ORTWillEvaluacion = new HashSet<ORTWillEvaluacion>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public int Representacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORTWillEvaluacion> ORTWillEvaluacion { get; set; }
    }
}
