//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnboardingRrhh.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORTEvaluacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORTEvaluacion()
        {
            this.ORTSkillEvaluacion = new HashSet<ORTSkillEvaluacion>();
            this.ORTWillEvaluacion = new HashSet<ORTWillEvaluacion>();
        }
    
        public int Id { get; set; }
        public int IdOnboarding { get; set; }
        public int NumeroEvaluacion { get; set; }
        public System.DateTime FechaPropuesta { get; set; }
        public Nullable<System.DateTime> FechaEvaluacion { get; set; }
        public Nullable<decimal> PuntuacionSkill { get; set; }
        public Nullable<decimal> PuntuacionWill { get; set; }
        public Nullable<decimal> PuntuacionTotal { get; set; }
        public string PuntosFuertes { get; set; }
        public string PuntosDesarrollar { get; set; }
        public string ComentariosEvaluador { get; set; }
        public string ComentariosEvaluado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public bool Activo { get; set; }
    
        public virtual ORTOnboarding ORTOnboarding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORTSkillEvaluacion> ORTSkillEvaluacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORTWillEvaluacion> ORTWillEvaluacion { get; set; }
    }
}
