//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnboardingRrhh.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORTOnboarding
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORTOnboarding()
        {
            this.ORTAsignacionRecurso = new HashSet<ORTAsignacionRecurso>();
            this.ORTEvaluacion = new HashSet<ORTEvaluacion>();
        }
    
        public int Id { get; set; }
        public int IdPlaza { get; set; }
        public int IdColaborador { get; set; }
        public int IdEstadoOnboarding { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORTAsignacionRecurso> ORTAsignacionRecurso { get; set; }
        public virtual ORTColaborador ORTColaborador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORTEvaluacion> ORTEvaluacion { get; set; }
        public virtual ORTPlaza ORTPlaza { get; set; }
    }
}
