//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnboardingRrhh.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORTSkillEvaluacion
    {
        public int Id { get; set; }
        public int IdEvaluacion { get; set; }
        public int IdSkill { get; set; }
        public int IdEstadoSkill { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public bool Activo { get; set; }
    
        public virtual ORTEstadoSkill ORTEstadoSkill { get; set; }
        public virtual ORTEvaluacion ORTEvaluacion { get; set; }
        public virtual ORTSkill ORTSkill { get; set; }
    }
}
